### ISSUE TITLE
jQuery needed a second time

### ISSUE THREAD

**Issue by pierre-H** [Sylius/AdminOrderCreationPlugin#110]
Hello,

I've got some custom jQuery code in the admin layout Template and because of this line https://github.com/Sylius/AdminOrderCreationPlugin/blob/bd2253dd16f26c3541afa1a98d2022473aecccf5/src/Resources/views/Order/selectCustomer.html.twig#L46 I've got some bugs.

Can someone explain to me why the re-import of jQuery is necessary (the admin already includes jQuery) ?

(jQuery was added in this commit https://github.com/Sylius/AdminOrderCreationPlugin/commit/f77949652272a503b35a90516d1a0ce0642ff24b)

Thank you in advance

**Comment by pierre-H** [comment]
up :)

**Comment by Zales0123** [comment]
Sorry, I totally missed it :) Yes, it should definitely not be duplicated, it's a bug 👍 Thank you for reporting that

**Comment by pierre-H** [comment]
Thank you @Zales0123
