### ISSUE TITLE
plugin installation issue

### ISSUE THREAD

**Issue by perfectwebtech** [Sylius/AdminOrderCreationPlugin#127]
help me for installation plugin i did try  php 7.0  with sylius so i can use all plugins installation
i am getting error  at  7.0 php version incompatibility 

anyone can help me or suggestion me ? i would like to install all plugins and library with sylius 

as 7.0 result here

 /opt/rh/rh-php70/root/bin/php -d memory_limit=-1 /usr/bin/composer require sylius/admin-order-creation-plugin

  [InvalidArgumentException]
  Package sylius/admin-order-creation-plugin at version  has a PHP requirement incompatible with your PHP version (7.0.27)

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

**Comment by kubaceg** [comment]
You must upgrade Your PHP version to 7.2. 7.0 version was supported to 01.01.2019 so it's time to upgrade :)

**Comment by Zales0123** [comment]
Sorry for the delay with answer, I've totally missed this issue. @kubaceg is right, PHP 7.2 and higher is supported, so I suggest to upgrade your PHP version :) Feel free to reopen the issue if you feel it's necessary. Good luck!
