### ISSUE TITLE
The payments contraint breaks the cart

### ISSUE THREAD

**Issue by bitbager** [Sylius/AdminOrderCreationPlugin#130]
`vendor/sylius/admin-order-creation-plugin/src/Resources/config/validation.xml` has a declaration of min/max count of 1 payment in the Order resource. That being said, at the cart stage where there are no payments at all it throws the Violation error and breaks the cart usability. Screenshot:

![Screenshot 2019-06-12 at 22 19 09](https://user-images.githubusercontent.com/28542010/59385389-8048a000-8d64-11e9-842a-19f6dbd3b563.png)

**Comment by Leobaillard** [comment]
Still an issue.

**Comment by hornofj** [comment]
Still an issue.
