### ISSUE TITLE
The migrations doesn't make sense

### ISSUE THREAD

**Issue by loevgaard** [Sylius/AdminOrderCreationPlugin#139]
Am I missing something or does the [two migration](https://github.com/Sylius/AdminOrderCreationPlugin/tree/master/migrations) files leave the database unchanged?

The first one adds to fields and the second one removes them?

If that's the case, why not remove these files? :)

**Comment by Zales0123** [comment]
Totally, it's just an offspring of the first approaches that were made at the beginning of the plugin implementation ;) We should remove them

**Comment by GSadee** [comment]
Fixed by #174
