### ISSUE TITLE
Sylius 1.7 compatibility

### ISSUE THREAD

**Issue by oallain** [Sylius/AdminOrderCreationPlugin#148]
Hi,

It would be great if this plugin was compatible with Sylius 1.7.

**Comment by knyk** [comment]
agreed. Twig templates are incompatible and while trying to create order I get redirected to `about:blank#blocked`

**Comment by radekbernatek** [comment]
> agreed. Twig templates are incompatible and while trying to create order I get redirected to `about:blank#blocked`

@knyk This is not AOCPlugin bug, you need to update friendsofsymfony/jsrouting-bundle to 2.5.4 because of https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/issues/379

**Comment by Roshyo** [comment]
This is now compatible with 1.7 (with 0.8 release)

**Comment by oallain** [comment]
Thanks @Roshyo :rocket: !
