### ISSUE TITLE
Zend\Stdlib and Laminas\Stdlib conflicts with Sylius 1.10

### ISSUE THREAD

**Issue by jdubuisson** [Sylius/AdminOrderCreationPlugin#180]
On a fresh Sylius install (1.10.5), I'm facing this error when trying to create an order :

> 
> Attempted to load class "PriorityQueue" from namespace "Zend\Stdlib".
> Did you forget a "use" statement for e.g. "Sylius\Bundle\FixturesBundle\Suite\PriorityQueue" or "Laminas\Stdlib\PriorityQueue"?

This is raised in `Sylius\AdminOrderCreationPlugin\ReorderProcessing\CompositeReorderProcessor`, which contains the only reference I could find to `PriorityQueue`.

It seems that `Laminas\Stdlib\PriorityQueue` is a drop-in replacement for `Zend\Stdlib\PriorityQueue`. It is required by Sylius 1.10.

I am not sure how to approach this. I changed the `use` statement locally in `CompositeReorderProcessor` and it works. However, this change would likely break the plugin for earlier versions of Sylius. I see that 1.9 is still covered in the plugin's `composer.json`.

Any ideas ?

**Comment by GSadee** [comment]
Fixed by #183
