### ISSUE TITLE
Lack of support for multiple payments

### ISSUE THREAD

**Issue by GSadee** [Sylius/AdminOrderCreationPlugin#52]
When we add two payments while creating an order, only the last of them will have the assigned currency code (look at [Sylius](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/OrderProcessing/OrderPaymentProcessor.php#L73:L79)).

And unfortunately, it causes an error:
<img width="1051" alt="zrzut ekranu 2018-07-24 o 11 25 52" src="https://user-images.githubusercontent.com/6140884/43129315-714139f2-8f34-11e8-80d5-046a562f629a.png">

**Comment by GSadee** [comment]
In my opinion, we should allow to choose only one payment method, as we don't have proper support for multiple payments in Sylius (the same applies to shipping method). 
If someone would like to use multiple payment/shipping methods, this behaviour should be implemented as a customization of Sylius and this plugin.

**Comment by CoderMaggie** [comment]
Let's introduce a validation for having only one payment method per order for now, and I will incorporate multiple payment methods into backlog.

**Comment by Zales0123** [comment]
Absolutely agreed for a single payment/shipping method 👍 I'm wondering should we even think about supporting multiple payments/shipment right now? We don't have such a functionality in Sylius and we're creating plugins for Sylius :) IMO we should focus on providing the best integration with base Sylius and make it as easy to extend/customize as it can be
