### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by Konafets** [Sylius/AdminOrderCreationPlugin#99]
After I copied the migration files, I issued the command `bin/console doctrine:migrations:migrate` which led me to the following error:

```
[Doctrine\DBAL\Migrations\MigrationException]
  Migration class "DoctrineMigrations\Version20180626065141" was not found. Is it placed in "DoctrineMigrations" namespace?
```

I had to change the namespace of the migration files from `Sylius\Migrations;` -> `DoctrineMigrations;`.

Not sure if this is a documentation or a code issue.

**Comment by Zales0123** [comment]
Hello Stefan, migrations namespace was changed in https://github.com/Sylius/AdminOrderCreationPlugin/pull/94 but no release has been made since this merge 😥 I'll release a `0.7` version of the plugin today and it will be available :)

**Comment by Zales0123** [comment]
Should not be an issue after https://github.com/Sylius/AdminOrderCreationPlugin/releases/tag/0.6.2 :)
